// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8az5MW8NI-7EMuRmO9ea0oHhzPq0s3F8',
    appId: '1:327239564108:web:227679b7bf6a645dd3ede9',
    messagingSenderId: '327239564108',
    projectId: 'smart-home-ptit',
    authDomain: 'smart-home-ptit.firebaseapp.com',
    storageBucket: 'smart-home-ptit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP_UMKjk9HM8ZYGj0PaCBUu5IAIy1rUG0',
    appId: '1:327239564108:android:1acd0437b31df021d3ede9',
    messagingSenderId: '327239564108',
    projectId: 'smart-home-ptit',
    storageBucket: 'smart-home-ptit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnga1rlcEVkjJsHzEI34XdF3w1NG7f3CA',
    appId: '1:327239564108:ios:8e3d84ada1926f1fd3ede9',
    messagingSenderId: '327239564108',
    projectId: 'smart-home-ptit',
    storageBucket: 'smart-home-ptit.appspot.com',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnga1rlcEVkjJsHzEI34XdF3w1NG7f3CA',
    appId: '1:327239564108:ios:d2b00f79c1dfc988d3ede9',
    messagingSenderId: '327239564108',
    projectId: 'smart-home-ptit',
    storageBucket: 'smart-home-ptit.appspot.com',
    iosBundleId: 'com.example.smartHome.RunnerTests',
  );
}
